config/routes.rb
Rails.application.routes.draw do

  root 'site#show'

  #users routes
  get '/signup', to: 'users#new'
  get '/profile', to: 'users#show'
  get '/edit_profile', to: 'users#edit'
  resources :users, only: [:create, :update]

  #sessions routes
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  resources :sessions, only: [:create]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :workouts
end

app/models/workout.rb
class Workout < ActiveRecord::Base

  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    unless current_user
      redirect_to login_path
    end
  end
  
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to profile_path
    else 
      render :new
  end
end

  #authenticate user, set session, redirect_to

  def create
    user = User.find_by_email(user_params[:email])
    if user && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to profile_path
    else 
      redirect_to login_path
    end
  end

  # clear session (logout user)
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:email, :password)
    end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end

  def index

  end

  def show
    render :show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    user = User.new(user_params)
    user.save
      session[:user_id] = user.id
      redirect_to profile_path
  end

  def show
  end

  def edit
    @user = User.find(current_user)
    render :edit
  end

  def update 
    user = User.find(params[:id])
    if current_user
      user.update_attributes(user_params)
      redirect_to profile_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user
      @user.destroy
      session[:user_id] = nil
      redirect_to root_path
    end
  end


  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :age, :sex, :weight, :height)
    end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutApp</title>
  
  <!-- bootstrap css -->
  <link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <%= stylesheet_link_tag :application, media: :all %>

  <%= csrf_meta_tags %>
</head>
  <body>
  <nav class="navbar-inverse">
    <div class="container">
      <div class="simple-nav">
        <%= link_to "Home", root_path %>
        <!-- creates spacing between links -->
        &nbsp;&nbsp;|&nbsp;&nbsp;
        
        <% if current_user %>
          <%= link_to "Profile", profile_path %>
          <!-- creates spacing between links -->
          &nbsp;&nbsp;|&nbsp;&nbsp;



          <%= link_to "Log Out", logout_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %>
          <!-- creates spacing between links -->
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to "Log In", login_path %>
        <% end %>

      </div>


      <%= yield %>
    </div>


    <%= javascript_include_tag :application %>
  </body>
</html>

app/views/site/about.html.erb
<h1>Site#about</h1>
<p>Find me in app/views/site/about.html.erb</p>

app/views/site/contact.html.erb
<h1>Site#contact</h1>
<p>Find me in app/views/site/contact.html.erb</p>

app/views/site/show.html.erb
<div class="col-xs-4 col-sm-6 col-md-8">
		<img class="muscle-man img-responsive" src="http://woldfitness.com/wp-content/uploads/2013/01/full-body-muscles.jpg">
</div>

app/views/users/edit.html.erb
<hr>
<div class="well">
  <h3><center>Edit Your Profile</center></h3>
</div>

<div class="container">
  <div class="col-sm-6 col-sm-offset-3">
    <br>
    <div class="signupbox">
      <%= form_for @user do |f| %>
        <%= f.label :name, "Name" %>:
        <%= f.text_field :name, class:"form-control", placeholder:"ex. MrMacintosh", required: true %><br />
        <%= f.label :email, "Email" %>:
        <%= f.email_field :email, class:"form-control", placeholder:"ex. hello@google.com", required: true %><br />
        <%= f.label :password, "Password" %>:
        <%= f.password_field :password, class:"form-control", placeholder:"don't use password as your password", required: true %><br />

        <%= f.label :age, "Age" %>:
        <%= f.text_field :age, class:"form-control", placeholder:"ex. 24", required: true %><br />
        <%= f.label :sex, "Gender" %>:
		<%= f.select :sex, %w{Male Female}, :prompt => 'Select', required: true, placeholder: 'Gender', class: 'form-control' %><br />
		<br> 
        <%= f.label :weight, "Weight" %>:
        <%= f.text_field :weight, class:"form-control", placeholder:"ex. 170 lbs", required: true %><br />
        <%= f.label :height, "Height" %>:
        <%= f.text_field :height, class:"form-control", placeholder:"ex. 6", required: true %><br /> 
        
        <%= f.submit "Update!", class:"btn btn-primary form-control" %>
      <% end %>
      <br>
      <br>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<hr>
<div class="well">
  <h3><center>Sign Up</center></h3>
</div>

<div class="container">
  <div class="col-sm-6 col-sm-offset-3">
    <br>
    <div class="signupbox">
      <%= form_for @user do |f| %>
        <%= f.label :name, "Name" %>:
        <%= f.text_field :name, class:"form-control", placeholder:"ex. MrMacintosh", required: true %><br />
        <%= f.label :email, "Email" %>:
        <%= f.email_field :email, class:"form-control", placeholder:"ex. hello@google.com", required: true %><br />
        <%= f.label :password, "Password" %>:
        <%= f.password_field :password, class:"form-control", placeholder:"don't use password as your password", required: true %><br /> 
        
        <%= f.submit "Join Us!", class:"btn btn-primary form-control" %>
      <% end %>
      <br>
      <br>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <h2>Hello <%= current_user.name %></h2>
    <hr>
    <p><strong>Email:</strong> <%= current_user.email %></p>
    <p><strong>Age:</strong> <%= current_user.age %></p>
    <p><strong>Sex:</strong> <%= current_user.sex %></p>
    <p><strong>Weight:</strong> <%= current_user.weight %></p>
    <p><strong>Height:</strong> <%= current_user.height %></p>

    <%= link_to "Edit Profile", edit_profile_path, class: "btn btn-default" %>


  </div>


        <div class="workout-title">
          <h1>My Workout Schedule</h1><hr>
       

              <ul class="nav nav-tabs" role="tablist">
                <li><a href="#day-1" role="tab" data-toggle="tab">Mon</a></li>
                <li><a href="#day-2" role="tab" data-toggle="tab">Tue</a></li>
                <li><a href="#day-3" role="tab" data-toggle="tab">Wed</a></li>
                <li><a href="#day-4" role="tab" data-toggle="tab">Thu</a></li>
                <li><a href="#day-5" role="tab" data-toggle="tab">Fri</a></li>
                <li><a href="#day-6" role="tab" data-toggle="tab">Sat</a></li>
                <li><a href="#day-7" role="tab" data-toggle="tab">Sun</a></li>
              </ul>
        </div>

   </div>
</div>